pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://maven.pkg.github.com/ReKri76/BlackJackEngine")
            credentials {
                username = 'RekRi76'
                password = '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'
            }
        }
    }
}

rootProject.name = "BlackJackMobile"
include ':app'
